import type { Metadata } from "next";
import { exo, lexendGiga, outfit, rubik, workSans } from './fonts'
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${exo.variable} ${lexendGiga.variable} ${outfit.variable} ${rubik.variable} ${workSans.variable}`}>
      <body>{children}</body>
    </html>
  )
}
